name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - ros1*
  pull_request:
    branches-ignore:
      - ros1*

jobs:
  industrial_ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble, iron, jazzy, rolling]
        ROS_REPO: [testing, main]
    env:
      ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
      ROS_REPO: ${{ matrix.ROS_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Source tests
        uses: "ros-industrial/industrial_ci@master"
